#!/usr/bin/env bash

# Quit is for the main menu. If Quit is 0, we will not exit the menu. When the user selects Quit,
# This value is changed to 1 and we will exit the main menu.
QUIT=0

# Saves screen so we can return to the previous screen later.
savescreen() {
  printf '\e[?1049h'
}

# Restores previous screen
restorescreen() {
  printf '\e[?1049l'
}

alias

mainmenu() {
  clear

  COLS=$(tput cols)
  COLS=$((COLS-2))
  ROWS=$(tput lines)
  ROWS=$((ROWS-10))
  gum style --border "rounded" --padding "1" --width="$COLS" --align="center" "xbpsman"
  printf "\e[7;${ROWS}r"
  tput cup 7 0 && tput ed
  MAINCHOICE=$(gum choose "Update all packages" "Search and add packages" "Remove installed packages" "Quit" --selected.background="4" --selected.foreground="16" --cursor="")
  case $MAINCHOICE in
    "Update all packages" )
      clear
      COLS=$(tput cols)
      COLS=$((COLS-2))
      ROWS=$(tput lines)
      ROWS=$((ROWS-10))
      gum style --border "rounded" --padding "1" --width="$COLS" --align="center" "Update all Packages"
      printf "\e[7;${ROWS}r"
      tput cup 7 0 && tput ed
      sudo xbps-install -Syu
      output=$(sudo xbps-install -Syu 2>&1)
      
      # Check for common error indicators in the output
      if echo "$output" | grep -q "ERROR"; then
        printf "An error occurred during the update.\nPress any key to continue"
      else
        printf "Packages updated\nPress any key to continue" 
      fi
      read -n1

            ;;
    "Search and add packages" )
      clear
      COLS=$(tput cols)
      COLS=$((COLS-2))
      ROWS=$(tput lines)
      ROWS=$((ROWS-8))
      gum style --border "rounded" --padding "1" --width="$COLS" --align="center" "Search and Add Packages"
      tput cup 7 0 && tput ed
      INSTALLPKGS=$(xbps-query -Rs "" | gum filter --no-limit --no-fuzzy --height=$ROWS)
      EXITERROR=$?
      if [[ $EXITERROR -ne 0 ]]; then
        printf "\e[7;${ROWS}r"
        tput cup 7 0
        printf "Exiting. Going back to main menu."
        sleep 3
      else    
        printf "\e[7;${ROWS}r"
        tput cup 7 0
        INSTALLPKGS=$(echo "$INSTALLPKGS" | grep -oP '\b[a-zA-Z0-9_-]+-\d+(\.\d+)*(_\d+)?\b')
        sudo xbps-install $INSTALLPKGS
        EXITERROR=$?
        if [[ $EXITERROR -eq 0 ]]; then
          printf "Installation succeeded \nPress any key to continue"
          read -n1
          clear
        else
          printf "Installation incomplete or completed with erros \nPress any key to continue"
          read -n1
          clear
        fi
      fi
    ;;
    "Remove installed packages" )
      clear
      COLS=$(tput cols)
      COLS=$((COLS-2))
      ROWS=$(tput lines)
      ROWS=$((ROWS-8))
      gum style --border "rounded" --padding "1" --width="$COLS" --align="center" "Remove installed packages"
      printf "\e[7;${ROWS}r"
      tput cup 7 0 && tput ed
      RMPKGS=$(xbps-query -s "" | gum filter --no-limit --no-fuzzy --height="$ROWS")
      EXITERROR=$?
      if [[ $EXITERROR -ne 0 ]]; then
        printf "\e[7;${ROWS}r"
        tput cup 7 0
        printf "Exiting. Going back to main menu."
        sleep 3
      else
        printf "\e[7;${ROWS}r"
        tput cup 7 0
        RMPKGS=$(echo $RMPKGS |  grep -oP '\b[a-zA-Z0-9_-]+-\d+(\.\d+)*(_\d+)?\b')
        sudo xbps-remove $RMPKGS
        EXITERROR=$?
        if [[ $EXITERROR -eq 0 ]]; then
          printf "Packages removed \nPress any key to continue"
          read -n1
          clear
        else printf "Package removal incomplete or completed with erros \nPress any key to continue"
          read -n1
          clear
        fi
      fi
    ;;
    "Quit" )
      QUIT=1
      ;;
  esac
      
}

savescreen
while [[ $QUIT -eq 0 ]]; do
  mainmenu
done

printf '\e[;r'
restorescreen
